"""Added new column to TestCase table

Revision ID: 40f8656c54f0
Revises: bc53537aea8c
Create Date: 2026-04-25 07:58:22.544792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f8656c54f0'
down_revision = 'bc53537aea8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.alter_column('function_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=250),
               type_=sa.String(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("'default_value'"))

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_problem_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_column('case_problem_id')

    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.alter_column('function_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=250),
               existing_nullable=False,
               existing_server_default=sa.text("'default_value'"))

    # ### end Alembic commands ###
