"""removed 3 columns in case problem table

Revision ID: 48fe3cf6440e
Revises: 63a6e769bae8
Create Date: 2026-04-26 19:13:04.475236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48fe3cf6440e'
down_revision = '63a6e769bae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('expected_output_3')
        batch_op.drop_column('expected_output_1')
        batch_op.drop_column('expected_output_2')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('input_data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('expected_output', sa.Text(), nullable=False))
        batch_op.drop_column('case_3')
        batch_op.drop_column('case_2')
        batch_op.drop_column('case_problem_id')
        batch_op.drop_column('case_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_1', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
        batch_op.add_column(sa.Column('case_problem_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('case_2', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
        batch_op.add_column(sa.Column('case_3', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
        batch_op.drop_column('expected_output')
        batch_op.drop_column('input_data')
        batch_op.drop_column('problem_id')

    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output_2', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('expected_output_1', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('expected_output_3', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))

    # ### end Alembic commands ###
