"""recovered expected output column for case problem table

Revision ID: 49fc5bf733e9
Revises: bb9f4eefeb93
Create Date: 2026-04-24 11:26:05.417865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fc5bf733e9'
down_revision = 'bb9f4eefeb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('expected_output')

    # ### end Alembic commands ###
