"""overwrite test_case column to three different columns

Revision ID: 50878451b7cd
Revises: 40f8656c54f0
Create Date: 2026-04-25 08:42:03.151184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50878451b7cd'
down_revision = '40f8656c54f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_1', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('case_2', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('case_3', sa.Text(), nullable=False))
        batch_op.drop_column('test_case')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_case', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
        batch_op.drop_column('case_3')
        batch_op.drop_column('case_2')
        batch_op.drop_column('case_1')

    # ### end Alembic commands ###
