"""Changed data type of columns in Administrator table

Revision ID: 5124086bf45b
Revises: 51faa36e823a
Create Date: 2026-05-05 07:45:43.902677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5124086bf45b'
down_revision = '51faa36e823a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.alter_column('admin_username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('admin_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.alter_column('admin_password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_nullable=False)
        batch_op.alter_column('admin_username',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
