"""added an administrator table

Revision ID: 51faa36e823a
Revises: 48fe3cf6440e
Create Date: 2026-04-30 14:03:43.560846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51faa36e823a'
down_revision = '48fe3cf6440e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('admin_password', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_column('admin_password')
        batch_op.drop_column('admin_username')

    # ### end Alembic commands ###
