"""added three new columns for three output relative to three test cases

Revision ID: 63a6e769bae8
Revises: 50878451b7cd
Create Date: 2026-04-25 08:52:10.865082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a6e769bae8'
down_revision = '50878451b7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expected_output_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expected_output_3', sa.Text(), nullable=True))
        batch_op.drop_column('expected_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.drop_column('expected_output_3')
        batch_op.drop_column('expected_output_2')
        batch_op.drop_column('expected_output_1')

    # ### end Alembic commands ###
