"""added difficulty column for history table

Revision ID: 694fecf6dfb4
Revises: d273a5e73584
Create Date: 2026-06-04 10:23:17.218097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694fecf6dfb4'
down_revision = 'd273a5e73584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
