"""added args and return type column

Revision ID: 6b34fa0e3c0a
Revises: 5124086bf45b
Create Date: 2026-05-06 08:32:08.386117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b34fa0e3c0a'
down_revision = '5124086bf45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('args', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('return_type', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('return_type')
        batch_op.drop_column('args')

    # ### end Alembic commands ###
