"""added difficulty column for case problem history

Revision ID: 8667a3a75f56
Revises: 694fecf6dfb4
Create Date: 2026-06-04 15:47:24.344284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8667a3a75f56'
down_revision = '694fecf6dfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem__history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem__history', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
