"""added a timestamped column for output problems

Revision ID: b3cebc53f273
Revises: 6b34fa0e3c0a
Create Date: 2026-05-09 10:27:59.629570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3cebc53f273'
down_revision = '6b34fa0e3c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_output_problems')
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('recent_output_problems',
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('problem_set', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('expected_output', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('difficulty', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('problem_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
