"""removed expected output column on case problem table

Revision ID: bb9f4eefeb93
Revises: 
Create Date: 2026-04-24 11:21:11.942422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb9f4eefeb93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('expected_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_output', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), server_default=sa.text("''"), nullable=True))

    # ### end Alembic commands ###
