"""Added a column for function names

Revision ID: bc53537aea8c
Revises: 49fc5bf733e9
Create Date: 2026-04-24 12:19:03.936793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc53537aea8c'
down_revision = '49fc5bf733e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('function_name')

    # ### end Alembic commands ###
