"""added check mutation flag and unordered flag in case problem 

Revision ID: d673771f2aff
Revises: 515d682f92f8
Create Date: 2026-06-20 11:31:44.347145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd673771f2aff'
down_revision = '515d682f92f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_mutation', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('unordered', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_problem', schema=None) as batch_op:
        batch_op.drop_column('unordered')
        batch_op.drop_column('check_mutation')

    # ### end Alembic commands ###
